### ISSUE TITLE
Name of this package.

### ISSUE THREAD

**Issue by mingwandroid** [conda-forge/nose_parameterized-feedstock#3]
I was just wondering why this is called nose_parameterized instead of nose-parameterized? I've been working on some theano fixes and it needs this package added to defaults, but from everything I've seen, the correct name is nose-parameterized (e.g. to get it from pypi with conda, you'd use `conda skeleton pypi nose-parameterized`).

**Comment by jakirkham** [comment]
You're right. It probably should be fixed. I don't recall why it was made `_` instead of `-`.

Also had added this for `theano` and it is also using `_` [currently](https://github.com/conda-forge/theano-feedstock/blob/6d1145f6ef597d4786fa186834ad250295b88eae/recipe/meta.yaml#L33).

**Comment by ocefpaf** [comment]
Fixed in #5. Thanks @mingwandroid!
